### PR TITLE
[Feature]: Redirect System.Object base type when member cloning

### PR DESCRIPTION
**Pull request by ds5678**
Related: #93

### CODE REVIEW

**Comment by Washi1337** [comment]
I think we should add a check that the scope of the type reference is a corlib name as well (e.g. using `KnownCorLibs.KnownCorLibNames`). It is technically possible to have a class in your own assembly called `System.Object`, without it actually being the `System.Object` that we mean here.

**Comment by ds5678** [comment]
I'll fix it 👍

**Comment by ds5678** [comment]
Should be good!

**Comment by Washi1337** [comment]
LGTM. Thanks.

**Review by Washi1337 — APPROVED** [review]

**Pull request merged**
