### PR TITLE
[Feature]: Add a SetSemanticMethods method to PropertyDefinition and EventDefinition

### LINKED ISSUE #168: Setter for PropertyDefinition.SetMethod and PropertyDefinition.GetMethod
## Problem Description
AsmResolver is currently lacking the ability to set the properties `SetMethod` and `GetMethod` of a PropertyDefinition. 

## Proposal
Implement a setter for the properties `SetMethod` and `GetMethod` of a PropertyDefinition in order to be able to set get and set accessors of properties.

## Alternatives
A property can be replaced by its get and set accessors and a corresponding field to host the value. 

## Additional context
Missing setter for  `PropertyDefinition.GetMethod` in AsmResolver (current state):
Missing setter in AsmResolver

Existing setter for `PropertyDef.GetMethod` in Dnlib (feature request):
Existing setter in dnlib

### PR DESCRIPTION
**Pull request by ds5678**
Closes #168 

I named these 2 methods `ApplyMethods`. Do you prefer them to be named something different?

### CODE REVIEW

**Comment by Washi1337** [comment]
`ApplyMethods` seems a bit weird or too generic of a name to me. Maybe something in the lines of `AddSemantics`, `SetSemantics`, `SetSemanticMethods`, `UpdateMethods` or `UpdateSemanticMethods`?

**Comment by ds5678** [comment]
I like your `SetSemanticMethods` suggestion. 👍

**Comment by ds5678** [comment]
Updated!

**Review by Washi1337 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
