### PR TITLE
Feature/ Add Documentation for CilOpCodes

### PR DESCRIPTION
**Pull request by ds5678**
This pull request adds documentation for the CilOpCodes class.

The lines for this were pulled from https://en.wikipedia.org/wiki/List_of_CIL_instructions

The only ones I couldn't find information for was the Prefix OpCodes.

### CODE REVIEW

**Comment by ds5678** [comment]
@Washi1337 I added links to the Microsoft documentation for each op code. Are there any changes you want me to make before I copy the xml docs to the `CilCode` enumeration?

**Comment by Washi1337** [comment]
Great idea to add the msdn links :) The comments LGTM now!

**Comment by ds5678** [comment]
I copied the comments to the enumeration. Unless something needs changed, it should be good for merging.

**Comment by Washi1337** [comment]
Thanks again !

**Pull request merged**
