### PR TITLE
Feature/ FromValue methods for DataBlobSignature and Constant

### PR DESCRIPTION
**Pull request by ds5678**
This pull request adds FromValue static methods to DataBlobSignature and Constant.

### CODE REVIEW

**Comment by Washi1337** [comment]
Great suggestion! My only point of critique here is that your tests are either named incorrectly, or they should only test the `DataBlobSignature.FromValue` instead of `Constant.FromValue`. I think both are fine, but let's be consistent :)

**Comment by ds5678** [comment]
How would you suggest I rename them?

**Comment by Washi1337** [comment]
My suggestion would be to either move the tests to the `ConstantTest` class, as your tests are mostly testing for the correct workings of `Constant.FromValue`, or change the `Constant.FromValue` calls to `DataBlobSignature.FromValue` so that they can stay in the `DataBlobSignatureTest` file.

**Comment by ds5678** [comment]
I originally thought about putting there, but I felt that they bloated the test class and took away from the other tests there. How do you feel about me making `ConstantTest` into a partial class with the FromValue tests in a file called `ConstantTest.FromValue.cs`?

**Comment by ds5678** [comment]
If you feel differently about the bloatedness, it doesn't bother me that much to dump them all into `ConstantTest.cs`.

**Comment by ds5678** [comment]
Whichever you prefer

**Comment by Washi1337** [comment]
> I originally thought about putting there, but I felt that they bloated the test class and took away from the other tests there. How do you feel about me making `ConstantTest` into a partial class with the FromValue tests in a file called `ConstantTest.FromValue.cs`?

That is a good point, yes I think this is the right solution. If you can do that I'll merge this PR.

**Comment by ds5678** [comment]
Done!

**Comment by Washi1337** [comment]
Perfect. Thanks again!

**Pull request merged**
