### PR TITLE
Feature/Language Version 10 Everywhere

### PR DESCRIPTION
**Pull request by ds5678**

### CODE REVIEW

**Comment by ds5678** [comment]
For some reason, AppVeyor does not acknowledge the existence of a 10th language version

**Comment by ds5678** [comment]
I think that should fix the build issue, but for security reasons, it's apparently not going to run the build. However, on my local machine, the projects successfully build and all tests pass.

**Comment by Washi1337** [comment]
> I think that should fix the build issue, but for security reasons, it's apparently not going to run the build. However, on my local machine, the projects successfully build and all tests pass.

@ds5678  I am not sure what you are referring to? AppVeyor has built your PR just fine? Or am I missing something?

**Comment by ds5678** [comment]
After I pushed the commit changing the appveyor script, it didn't indicate that it was running. I assumed it was a security feature.

**Comment by Washi1337** [comment]
Not sure what happened there then. Either way, I will merge this.

**Pull request merged**
